services:
  mywordpress:
    image: wordpress
    restart: always
    ports:
      - ${WP_PORT}:80
      
      # or just env_file: ./env_1
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER} 
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - wordpress-vol:/var/www/html

  db: 
    image: mysql:5.7
    restart: always
      # or just env_file: ./env_2
    environment: 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD:  ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db-vol:/var/lib/mysql

volumes:  
  wordpress-vol: 
  db-vol:
